package compilador;

import java.util.HashMap;
import java.util.Map;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mauricio
 */
public class JExibicaoResultados extends javax.swing.JDialog {

    HashMap<String, Integer> hashContadorPalavras;

    /**
     * Creates new form JExibicaoResultados
     * @param parent
     * @param modal
     * @param mapa
     */
    public JExibicaoResultados(java.awt.Frame parent, boolean modal, HashMap<String, Integer> mapa) {
        super(parent, modal);
        initComponents();
        init(mapa);

    }

    private void init(HashMap mapa) {
        hashContadorPalavras = mapa;
        initTabela();
        atualizarTabela();
    }

    public void initTabela() {
        DefaultTableModel tm = new DefaultTableModel();

        tm.addColumn("Palavra");
        tm.addColumn("Quantidade");

        jTable.setModel(tm);

        jTable.getColumn("Quantidade").setPreferredWidth(500);
    }

    public void atualizarTabela() {
        DefaultTableModel tm = (DefaultTableModel) jTable.getModel();
        for (Map.Entry<String, Integer> entry : hashContadorPalavras.entrySet()) {
            String chave = entry.getKey();
            Integer valor = entry.getValue();
            Object[] row = new Object[2];
            row[0] = chave;
            row[1] = valor;
            tm.addRow(row);
        }
        jTable.setModel(tm);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_Header = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel_Content = new javax.swing.JPanel();
        jScrollPane = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        jPanel_Footer = new javax.swing.JPanel();
        jButton_Fechar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel_Header.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel1.setText("Resultados");
        jPanel_Header.add(jLabel1);

        getContentPane().add(jPanel_Header, java.awt.BorderLayout.NORTH);

        jPanel_Content.setLayout(new java.awt.BorderLayout());

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane.setViewportView(jTable);

        jPanel_Content.add(jScrollPane, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel_Content, java.awt.BorderLayout.CENTER);

        jButton_Fechar.setText("Fechar");
        jButton_Fechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_FecharActionPerformed(evt);
            }
        });
        jPanel_Footer.add(jButton_Fechar);

        getContentPane().add(jPanel_Footer, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_FecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_FecharActionPerformed
        dispose();
        setVisible(false);
    }//GEN-LAST:event_jButton_FecharActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JExibicaoResultados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JExibicaoResultados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JExibicaoResultados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JExibicaoResultados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JExibicaoResultados dialog = new JExibicaoResultados(new javax.swing.JFrame(), true, new HashMap<>());
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Fechar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel_Content;
    private javax.swing.JPanel jPanel_Footer;
    private javax.swing.JPanel jPanel_Header;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JTable jTable;
    // End of variables declaration//GEN-END:variables
}
